[project]
name = "taskboard"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "alembic>=1.20.0",
    "fastapi[standard]>=0.141.1",
    "psycopg[binary]>=3.3.6",
    "sqlmodel>=0.0.42",
]

[tool.fastapi]
entrypoint="app.main:app"
